const veriler = {
  turkish: {
    Individual: "Bireysel",
    Trainings: "Eğitimler",
    Services: "Hizmetler",
    AboutUs: "Hakkımızda",
    Vision: "Vizyon",
    Mission: "Misyon",
    Values: "Değerler",
    Contact: "İletişim",
    Wearelisteningtoyou: "Sizi Dinliyoruz",
    Institutional: "Kurumsal",
    Individual2: "Bireysel",
    Coaching: "Koçluk",
    Mentoring: "Mentorluk",
    Consulting: "Danışmanlık",
  },
  english: {
    Individual: "Individual",
    Trainings: "Trainings",
    Services: "Services",
    AboutUs: "About Us",
    Vision: "Vision",
    Mission: "Mission",
    Values: "Values",
    Contact: "Contact",
    Wearelisteningtoyou: "We Are Listening To You",
    Institutional: "Institutional",
    Individual2: "Individual",
    Coaching: "Coaching",
    Mentoring: "Mentoring",
    Consulting: "Consulting",
  },
};

export default veriler;
